project:
  type: website
  output-dir: out
  render:
    - "README.qmd"
    - "analysis/topography/index.qmd"
    - "antarctic-map/index.qmd"
  resources:
    - "/data/bedmap2/*.tif"
    - "/data/bedmap2/*.geojson"
    - "/data/nsidc/*.geojson"
    - "/data/nsidc/*.csv"
    - "/antarctic-map/antarcticmap-banner.png"
  
# only re-render if the source changes or if we specifically render that file
execute:
  freeze: auto
