project:
  type: website
  output-dir: out
  render:
    - "analysis/*"
    - "*.qmd"
  resources:
    - "/data/bedmap2/*.tif"
    - "/data/bedmap2/*.geojson"
    - "/data/nsidc/*.geojson"
  
# only re-render if the source changes or if we specifically render that file
execute:
  freeze: auto
